<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python-practice/blob/main/Pandas_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data={
    'Name':['Alice','Bob','Claire','syam','karthik','siddhu','mahesh','fardeen','teja','saaqib'],
    'Gender':['Female','Male','Female','Male','Male','Female','Male','Male','Male','Male'],
    'grade':['A','B','A','A','c','B','A','B','A','B'],
    'marks':[25,30,27,22,65,47,88,79,66,92]
}
df=pd.DataFrame(data)
df

      Name  Gender grade  marks
0    Alice  Female     A     25
1      Bob    Male     B     30
2   Claire  Female     A     27
3     syam    Male     A     22
4  karthik    Male     c     65
5   siddhu  Female     B     47
6   mahesh    Male     A     88
7  fardeen    Male     B     79
8     teja    Male     A     66
9   saaqib    Male     B     92

In [3]:
df.groupby('grade').count()

       Name  Gender  marks
grade
A         5       5      5
B         4       4      4
c         1       1      1

In [4]:
df.groupby('grade')['marks'].mean()

grade
A    45.6
B    62.0
c    65.0
Name: marks, dtype: float64

In [5]:
df.groupby('grade')['marks'].max()

grade
A    88
B    92
c    65
Name: marks, dtype: int64

In [17]:

df.groupby('Gender')['marks'].agg(['mean','median','min','max','count','sum'])

             mean  median  min  max  count  sum
Gender
Female  33.000000    27.0   25   47      3   99
Male    63.142857    66.0   22   92      7  442

In [7]:
df.groupby('Gender')['marks'].agg(Average='mean',median='median',lowest='min',highest='max')

          Average  median  lowest  highest
Gender
Female  33.000000    27.0      25       47
Male    63.142857    66.0      22       92

In [8]:
df

      Name  Gender grade  marks
0    Alice  Female     A     25
1      Bob    Male     B     30
2   Claire  Female     A     27
3     syam    Male     A     22
4  karthik    Male     c     65
5   siddhu  Female     B     47
6   mahesh    Male     A     88
7  fardeen    Male     B     79
8     teja    Male     A     66
9   saaqib    Male     B     92

In [9]:
reg1=pd.DataFrame({'id':[1,2,3],'name':['Manoj','gsfejh','Arham']})
reg2=pd.DataFrame({'id':[1,2,3],'marks':[96,44,33]})

pd.merge(reg1,reg2,on='id')

   id    name  marks
0   1   Manoj     96
1   2  gsfejh     44
2   3   Arham     33

In [19]:
reg1=pd.DataFrame({'id':[1,2,3],'name':['Manoj','gsfejh','Arham']})
reg2=pd.DataFrame({'id':[1,2,3],'marks':[96,44,39]})

pd.merge(reg1,reg2,on='id',how='inner')

   id    name  marks
0   1   Manoj     96
1   2  gsfejh     44
2   3   Arham     39

In [11]:
reg1=pd.DataFrame({'id':[1,2,3],'name':['Manoj','gsfejh','Arham']})
reg2=pd.DataFrame({'id':[1,2,3],'marks':[96,44,39]})

pd.merge(reg1,reg2,on='id',how='left')

   id    name  marks
0   1   Manoj     96
1   2  gsfejh     44
2   3   Arham     39

In [12]:
reg1=pd.DataFrame({'id':[1,2,3],'name':['Manoj','gsfejh','Arham']})
reg2=pd.DataFrame({'id':[1,2,3],'marks':[96,44,39]})

pd.concat([reg1,reg2])

   id    name  marks
0   1   Manoj    NaN
1   2  gsfejh    NaN
2   3   Arham    NaN
0   1     NaN   96.0
1   2     NaN   44.0
2   3     NaN   39.0

In [13]:
reg1=pd.DataFrame({'id':[1,2,3],'name':['Manoj','gsfejh','Arham']})
reg2=pd.DataFrame({'c':[81,24,53],'marks':[96,44,39]})

pd.concat([reg1,reg2],axis=1)

   id    name   c  marks
0   1   Manoj  81     96
1   2  gsfejh  24     44
2   3   Arham  53     39